<?php

namespace Modules\Bil\Livewire\RawMaterials\Reports;

use Illuminate\Support\Facades\DB;
use Livewire\Attributes\Title;
use Modules\Bil\Models\RawMaterialDelivery;
use Modules\Bil\Models\RawMaterialItem;

/**
 * Reports → Supplier Deliveries. What suppliers delivered — the barcodes
 * generated by the Supplier Deliveries page, over `rawmaterials_supplier_deliveries`
 * (the delivery-staging table). Renamed from the legacy "Items Received" report.
 *
 * Edit (weight) and delete are DISABLED once a delivery has been received into
 * the warehouse (its barcode exists in `rawmaterials_warehouse_entry`), because
 * from that point the item has progressed and stock depends on it. Deliveries
 * are pre-stock, so removing an un-received one has no stock effect.
 */
#[Title('Supplier Deliveries Report')]
class SupplierDeliveries extends RawMaterialReport
{
    protected ?array $optCache = null;

    public function title(): string
    {
        return 'Supplier Deliveries Report';
    }

    public function printKey(): string
    {
        return 'supplier-deliveries';
    }

    public function subtitle(): string
    {
        return 'Raw material delivered by suppliers (barcodes generated at Supplier Deliveries).';
    }

    protected function options(): array
    {
        return $this->optCache ??= [
            'suppliers' => DB::connection('bil')->table('rawmaterials_supplier')
                ->orderBy('suppliername')->pluck('suppliername', 'suppliercode')->all(),
            'products' => DB::connection('bil')->table('rawmaterials_products')
                ->orderBy('productname')->pluck('productname', 'id')->all(),
            'groups' => DB::connection('bil')->table('rawmaterials_groups')
                ->orderBy('groupname')->pluck('groupname', 'id')->all(),
            'subgroups' => DB::connection('bil')->table('rawmaterials_subgroups')
                ->orderBy('subgroupname')->pluck('subgroupname', 'id')->all(),
        ];
    }

    public function filterDefs(): array
    {
        $o = $this->options();

        return [
            'supplier' => ['label' => 'Supplier', 'options' => $o['suppliers']],
            'group' => ['label' => 'Group', 'options' => $o['groups']],
            'subgroup' => ['label' => 'Sub Group', 'options' => $o['subgroups']],
            'product' => ['label' => 'Product', 'options' => $o['products']],
        ];
    }

    /**
     * Show full numbered pagination (with a total) on any date span — the base
     * would drop to count-free prev/next past ~92 days, which reads as "only 25
     * rows". The total comes from the fast join-free paginationTotal() below.
     * Only fall back to count-free when a joined-column predicate is active
     * (group/sub-group filter, or a name search), since those can't be counted
     * without the display joins.
     */
    public function usesSimplePagination(): bool
    {
        return ($this->filters['group'] ?? '') !== ''
            || ($this->filters['subgroup'] ?? '') !== ''
            || $this->search !== '';
    }

    /**
     * A fast total for the default view: count the base deliveries table with
     * the date range + supplier/product filters applied (all indexed base
     * columns, no display joins). Null for summaries or when a joined predicate
     * is active (usesSimplePagination() is true then, so this isn't consulted).
     */
    protected function paginationTotal(array $view): ?int
    {
        if (($view['type'] ?? 'table') !== 'table') {
            return null;
        }
        if (($this->filters['group'] ?? '') !== '' || ($this->filters['subgroup'] ?? '') !== '' || $this->search !== '') {
            return null;
        }

        $q = DB::connection('bil')->table('rawmaterials_supplier_deliveries');
        $this->applyDate($q, 'dateofcreation', slash: true);
        $this->applyFilters($q, [
            'supplier' => 'suppliercode',
            'product' => 'productid',
        ]);

        return $q->count();
    }

    /** Base joined + filtered query over the deliveries table. */
    protected function base()
    {
        $q = DB::connection('bil')->table('rawmaterials_supplier_deliveries as c')
            ->leftJoin('rawmaterials_products as p', 'c.productid', '=', 'p.id')
            ->leftJoin('rawmaterials_groups as g', 'p.groupid', '=', 'g.id')
            ->leftJoin('rawmaterials_subgroups as sg', 'p.subgroupid', '=', 'sg.id');

        $this->applyDate($q, 'c.dateofcreation', slash: true);
        $this->applyFilters($q, [
            'supplier' => 'c.suppliercode',
            'product' => 'c.productid',
            'group' => 'p.groupid',
            'subgroup' => 'p.subgroupid',
        ]);

        return $q;
    }

    public function views(): array
    {
        return [
            'default' => [
                'label' => 'Default',
                'type' => 'table',
                'columns' => [
                    ['Barcode', 'barcode'],
                    ['Supplier', 'suppliercode'],
                    ['Group', 'groupname'],
                    ['Sub Group', 'subgroupname'],
                    ['Product', 'productname'],
                    ['Weight (kg)', 'weight'],
                    $this->dateCol('Date', 'dateofcreation'),
                ],
                'searchable' => ['c.barcode', 'c.suppliercode', 'p.productname', 'g.groupname', 'sg.subgroupname'],
                'query' => fn () => $this->base()
                    ->select('c.id', 'c.barcode', 'c.suppliercode', 'c.weight', 'c.dateofcreation',
                        'g.groupname', 'sg.subgroupname', 'p.productname')
                    ->orderByDesc('c.id'),
            ],
            'by_product' => [
                'label' => 'Summary (by product)',
                'type' => 'summary',
                'columns' => [
                    ['Product', 'productname'],
                    ['Quantity', 'quantity'],
                    ['Weight (kg)', 'weight'],
                ],
                'searchable' => ['p.productname'],
                'query' => fn () => $this->base()
                    ->selectRaw('p.productname, COUNT(*) as quantity, SUM(c.weight) as weight')
                    ->groupBy('p.productname')->orderByDesc(DB::raw('SUM(c.weight)')),
            ],
            'by_subgroup' => [
                'label' => 'Summary (by sub group)',
                'type' => 'summary',
                'columns' => [
                    ['Sub Group', 'subgroupname'],
                    ['Quantity', 'quantity'],
                    ['Weight (kg)', 'weight'],
                ],
                'searchable' => ['sg.subgroupname'],
                'query' => fn () => $this->base()
                    ->selectRaw('sg.subgroupname, COUNT(*) as quantity, SUM(c.weight) as weight')
                    ->groupBy('sg.subgroupname')->orderByDesc(DB::raw('SUM(c.weight)')),
            ],
        ];
    }

    public function editFields(): array
    {
        return ['weight' => ['label' => 'Weight (kg)']];
    }

    /** Disable edit/delete once the delivery has been received into the warehouse. */
    protected function receivedGuard($row): ?string
    {
        if ($row && RawMaterialItem::where('barcode', $row->barcode)->exists()) {
            return 'Already received into the warehouse — cannot modify a received delivery.';
        }

        return null;
    }

    public function editGuard($row): ?string
    {
        return $this->receivedGuard($row);
    }

    public function deleteGuard($row): ?string
    {
        return $this->receivedGuard($row);
    }

    protected function findRow(int $id)
    {
        return RawMaterialDelivery::query()->find($id);
    }

    protected function fillEdit(int $id): void
    {
        $this->edit = ['weight' => (float) (RawMaterialDelivery::whereKey($id)->value('weight') ?? 0)];
    }

    public function saveEdit(): void
    {
        RawMaterialDelivery::whereKey($this->editingId)->update([
            'weight' => (float) ($this->edit['weight'] ?? 0),
        ]);
    }

    protected function performDelete(int $id): void
    {
        RawMaterialDelivery::whereKey($id)->delete();
    }
}
